### ISSUE TITLE
Parrafo abajo de titulo con descripcion corta

### ISSUE THREAD

**Issue by julian-alarcon** [alaventa/alaventa#2]
Aviso con informacion adicional:

`Se aceptan pagos por Nequi, Paypal, Colpatria o efectivo` y detalles de descuento (Descuento por ser primeros en tener enlace y por vivir en Duo33).

`Al hacer clic sobre las imagenes encontrás mas informacion (descripcion o imagenes)`

**Comment by milenasuarezl** [comment]
Listo mono
