### ISSUE TITLE
Casilla COMPRAR verde debajo de cada producto

### ISSUE THREAD

**Issue by julian-alarcon** [alaventa/alaventa#3]
Seccion/casilla debajo de cada producto con nombre `COMPRAR` y con icono de WhatsApp.
Debe redirigir a mensaje de WhatsApp con mensaje inicial del nombre del producto

`https://api.whatsapp.com/send?phone=NUMEROCELULAR&text=Hola%2C%20quiero%20comprar%20NOMBREPRODUCTO`

**Comment by milenasuarezl** [comment]
Listo mono
